In [1]:
import pandas as pd

cv = pd.read_parquet("recruitment-dataset-candidate-profiles-english.parquet")
job = pd.read_parquet("recruitment-dataset-job-descriptions-english.parquet")

cv.head()

,Position,Moreinfo,Looking For,Highlights,Primary Keyword,English Level,Experience Years,CV,CV_lang,id,__index_level_0__
0,"13 years of exp || Solidity, C#, JavaScript ||...",Who am I:\r\n- 13 years of commercial experien...,I am interested in:\r\n- part-time engagement;...,Landed a role of Director of Blockchain Develo...,Lead,fluent,11.0,Landed a role of Director of Blockchain Develo...,en,50534b61-6826-52b1-9ac5-bfd2cfa348ec,24230
1,1c Developer,Worked on a mobile application for tracking trips,None,None,Other,intermediate,3.0,\nWorked on a mobile application for tracking ...,en,c2b9ea56-b5c8-50ec-a63b-053a5c8ff467,24231
2,1C developer,1 am an 1C developer. I deployed an 1C to typo...,None,None,Flutter,intermediate,11.0,\n1 am an 1C developer. I deployed an 1C to ty...,en,b3bfe3ed-ec25-56b2-8aaa-8c629120538e,24232
3,1C Developer,Perfect knowledge of 1C:Enterprise Platform.\...,None,None,Other,intermediate,11.0,\nPerfect knowledge of 1C:Enterprise Platform...,en,163fb9a3-3695-5dc3-b1d0-e0038ce4d0a5,24233
4,#1 Customer Support Specialist,"Tech addicted, experienced customer support wi...",In terms of the nature of the Customer Support...,"thousands of resolved problems, also, thousand...",Support,fluent,2.5,"thousands of resolved problems, also, thousand...",en,3f201183-db58-5333-9139-74c16059dc4a,24234

In [2]:
job.head()

,Position,Long Description,Company Name,Exp Years,Primary Keyword,English Level,Published,Long Description_lang,id,__index_level_0__
0,10 + Blockchain Nodes / Masternodes to set up,*Requirements*\r\n\r\nWe're looking for a long...,MyCointainer,2y,Sysadmin,intermediate,2020-10-01T00:00:00+03:00,en,c0ca96e7-85df-50df-a64e-d934cd02a170,27461
1,10 .NET Developers (Middle and Senior level),"Greetings! My name is Maria, I am in urgent ne...",TechScout.tech,2y,.NET,intermediate,2022-03-01T00:00:00+02:00,en,64f4b7ea-36e4-5bdd-a8b1-185f32f7dc7f,27462
2,"10X Engineer (co-founder, #4 employee, USD 11-...",**Product**\r\nThe product is a live video cha...,Innoteka,5y,JavaScript,fluent,2021-07-01T00:00:00+03:00,en,b9a1303e-dd0c-5ed1-8f62-be2bc4c7da4f,27463
3,16 - Amazon Brand Manager,"Currently, TCM expanding its activities to Ukr...",FirstFive,2y,Marketing,upper,2022-01-01T00:00:00+02:00,en,99cb3f4a-9b4b-53d9-9a3b-bab2c22da346,27464
4,16 - Amazon Brand Manager,"Hello,\r\nWe, MIMIRB2B, are an outstaff compan...",MimirB2B,1y,Marketing,upper,2021-12-01T00:00:00+02:00,en,bc1419f7-28e2-582b-8d53-22e28b2f0210,27465

In [3]:
cv.columns.tolist(), job.columns.tolist()

(['Position',
  'Moreinfo',
  'Looking For',
  'Highlights',
  'Primary Keyword',
  'English Level',
  'Experience Years',
  'CV',
  'CV_lang',
  'id',
  '__index_level_0__'],
 ['Position',
  'Long Description',
  'Company Name',
  'Exp Years',
  'Primary Keyword',
  'English Level',
  'Published',
  'Long Description_lang',
  'id',
  '__index_level_0__'])

In [4]:
cv = cv.drop(columns=["CV_lang", "__index_level_0__"], errors="ignore")
job = job.drop(columns=["Long Description_lang", "__index_level_0__"], errors="ignore")

In [ ]:
cv.head()

# field CV sẽ được tổng hợp từ các trường như: Highlights, Moreinfo, Looking For

# field Position không chắc là “chức danh công việc chuẩn”, mà giống tiêu đề ứng viên tự viết

,Position,Moreinfo,Looking For,Highlights,Primary Keyword,English Level,Experience Years,CV,id
0,"13 years of exp || Solidity, C#, JavaScript ||...",Who am I:\r\n- 13 years of commercial experien...,I am interested in:\r\n- part-time engagement;...,Landed a role of Director of Blockchain Develo...,Lead,fluent,11.0,Landed a role of Director of Blockchain Develo...,50534b61-6826-52b1-9ac5-bfd2cfa348ec
1,1c Developer,Worked on a mobile application for tracking trips,None,None,Other,intermediate,3.0,\nWorked on a mobile application for tracking ...,c2b9ea56-b5c8-50ec-a63b-053a5c8ff467
2,1C developer,1 am an 1C developer. I deployed an 1C to typo...,None,None,Flutter,intermediate,11.0,\n1 am an 1C developer. I deployed an 1C to ty...,b3bfe3ed-ec25-56b2-8aaa-8c629120538e
3,1C Developer,Perfect knowledge of 1C:Enterprise Platform.\...,None,None,Other,intermediate,11.0,\nPerfect knowledge of 1C:Enterprise Platform...,163fb9a3-3695-5dc3-b1d0-e0038ce4d0a5
4,#1 Customer Support Specialist,"Tech addicted, experienced customer support wi...",In terms of the nature of the Customer Support...,"thousands of resolved problems, also, thousand...",Support,fluent,2.5,"thousands of resolved problems, also, thousand...",3f201183-db58-5333-9139-74c16059dc4a

In [ ]:
job.head()

,Position,Long Description,Company Name,Exp Years,Primary Keyword,English Level,Published,id
0,10 + Blockchain Nodes / Masternodes to set up,*Requirements*\r\n\r\nWe're looking for a long...,MyCointainer,2y,Sysadmin,intermediate,2020-10-01T00:00:00+03:00,c0ca96e7-85df-50df-a64e-d934cd02a170
1,10 .NET Developers (Middle and Senior level),"Greetings! My name is Maria, I am in urgent ne...",TechScout.tech,2y,.NET,intermediate,2022-03-01T00:00:00+02:00,64f4b7ea-36e4-5bdd-a8b1-185f32f7dc7f
2,"10X Engineer (co-founder, #4 employee, USD 11-...",**Product**\r\nThe product is a live video cha...,Innoteka,5y,JavaScript,fluent,2021-07-01T00:00:00+03:00,b9a1303e-dd0c-5ed1-8f62-be2bc4c7da4f
3,16 - Amazon Brand Manager,"Currently, TCM expanding its activities to Ukr...",FirstFive,2y,Marketing,upper,2022-01-01T00:00:00+02:00,99cb3f4a-9b4b-53d9-9a3b-bab2c22da346
4,16 - Amazon Brand Manager,"Hello,\r\nWe, MIMIRB2B, are an outstaff compan...",MimirB2B,1y,Marketing,upper,2021-12-01T00:00:00+02:00,bc1419f7-28e2-582b-8d53-22e28b2f0210